[package]
name = "civilization_control"
edition = "2024.beta"

[dependencies]
world = { local = "../../vendor/world-contracts/contracts/world" }

[environments]
testnet_internal = "4c78adac"
testnet_utopia = "4c78adac"
testnet_stillness = "4c78adac"
